name: EC2 CI

on:
  push:
    branches: [ "master" ]
    
  workflow_dispatch:

jobs:
  EC2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/checkout@v3
        with:
          node-version: 16.x

      - name: Installing dependencies
        run: npm install

      - name: Compiling typescript
        run: npm run build
        
      - name: Updating files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "dist, package.json, tsconfig.json"
          target: nodejs-aws-ci
              
      - name: Updating API dependencies
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: | 
            cd ~/nodejs-aws-ci
            npm install --omit=dev
            pm2 restart nodeapp
